//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tetris.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to konec.
        /// </summary>
        internal static string MENU_QUIT {
            get {
                return ResourceManager.GetString("MENU_QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        internal static string MENU_RESTART {
            get {
                return ResourceManager.GetString("MENU_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pokracovat.
        /// </summary>
        internal static string MENU_RESUME {
            get {
                return ResourceManager.GetString("MENU_RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabulka skore.
        /// </summary>
        internal static string MENU_SCOREBOARD {
            get {
                return ResourceManager.GetString("MENU_SCOREBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string MENU_START {
            get {
                return ResourceManager.GetString("MENU_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec hry, přejete si začít znovu?.
        /// </summary>
        internal static string MSG_ENDGAME {
            get {
                return ResourceManager.GetString("MSG_ENDGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejete si hru vypnout?.
        /// </summary>
        internal static string MSG_QUITGAME {
            get {
                return ResourceManager.GetString("MSG_QUITGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konec hry.
        /// </summary>
        internal static string TITLE_ENDGAME {
            get {
                return ResourceManager.GetString("TITLE_ENDGAME", resourceCulture);
            }
        }
    }
}
